Handle nslooup test within post-install

diff --git a/pkg/couldinho-base.install b/pkg/couldinho-base.install
--- a/pkg/couldinho-base.install
+++ b/pkg/couldinho-base.install
@@ -1,3 +1,43 @@
+function can_resolve_hostname {
+    if ping -q -c 1 -W 1 www.example.com > /dev/null 2>&1; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+function install_config_files {
+    
+    if [ -n $CONF_FILE_LOCATION ]; then
+
+        FILENAME="base-conf-files.tar.gz"
+        TMP_LOC=/tmp/base-conf-files
+
+        # Use the IP when available (eg. during pacstrap)
+        if [ -n $CONF_FILE_IP ]; then
+            curl -kL $CONF_FILE_IP/$FILENAME.aes -o /tmp/$FILENAME.aes
+        else
+            curl -kL $CONF_FILE_LOCATION/$FILENAME.aes -o /tmp/$FILENAME.aes
+        fi
+
+        openssl aes-256-cbc -d \
+            -salt \
+            -in /tmp/$FILENAME.aes \
+            -out /tmp/$FILENAME \
+            -k $CONF_FILE_PASS
+            #-iter 10000 \ # This isn't enabled in ubuntu yet
+
+        tar xf /tmp/$FILENAME -C /tmp/
+        #sed -i "s#TMP_LOC=#TMP_LOC=$TMP_LOC#g" /tmp/base-conf-files/run.sh
+        $TMP_LOC/run.sh $USER $password
+
+    else
+
+        echo "No config files selected"
+
+    fi
+}
+
 post_install() {
     post_upgrade
 }
@@ -26,33 +66,13 @@ post_upgrade() {
     cp /etc/conf.d/couldinho-snapper /etc/conf.d/snapper
 
     # Pull and decrypt sensitive configuration files
-    if [ -n $CONF_FILE_LOCATION ]; then
-
-        FILENAME="base-conf-files.tar.gz"
-        TMP_LOC=/tmp/base-conf-files
-
-        # Use the IP when available (eg. during pacstrap)
-        if [ -n $CONF_FILE_IP ]; then
-            curl -kL $CONF_FILE_IP/$FILENAME.aes -o /tmp/$FILENAME.aes
-        else
-            curl -kL $CONF_FILE_LOCATION/$FILENAME.aes -o /tmp/$FILENAME.aes
-        fi
-
-        openssl aes-256-cbc -d \
-            -salt \
-            -in /tmp/$FILENAME.aes \
-            -out /tmp/$FILENAME \
-            -k $CONF_FILE_PASS
-            #-iter 10000 \ # This isn't enabled in ubuntu yet
-
-        tar xf /tmp/$FILENAME -C /tmp/
-        #sed -i "s#TMP_LOC=#TMP_LOC=$TMP_LOC#g" /tmp/base-conf-files/run.sh
-        $TMP_LOC/run.sh $USER $password
-
+    if ! can_resolve_hostname; then
+        echo "===="
+        echo "* Cannot resolve hostnames, probably due to being in pacstrap."
+        echo "* This script should be handled by the install script instead."
+        echo "==="
     else
-
-        echo "No config files selected"
-
+        install_config_files
     fi
 
     # Start services
